version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mywebsite_app
    restart: always
    environment:
      - ENV=production
    networks:
      - my_network

  caddy:
    image: caddy:latest
    container_name: mywebsite_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - my_network

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_new
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300
    networks:
      - my_network

volumes:
  caddy_data:
  caddy_config:

networks:
  my_network:
    driver: bridge
